version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=soimalfath
      - DB_PASSWORD=Soimaquariuz2
      - DB_NAME=crudnest
      - NODE_ENV=development
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Soimaquariuz2
      - MYSQL_DATABASE=crudnest
      - MYSQL_USER=soimalfath
      - MYSQL_PASSWORD=Soimaquariuz2
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data: